### ISSUE TITLE
beets-alternatives plugin

### ISSUE THREAD

**Issue by rawdlite** [linuxserver/docker-beets#59]
Hi,
	
Great project.
Would you consider including the beets-alternatives plugin into the base image?
(https://github.com/geigerzaehler/beets-alternatives)

It basically supports 2 usecases.
- Export a subset of the collection for mobile players
- Create alternative path tree of linked files. 
   This can be used for example to access HighRes files via DLNA. 

I can do a Pull Request if this helps.
Cheers.

**Comment by thelamer** [comment]
I would really like if a power user could pick up and build a "heavy" modification layer for this image that installs tons of deps and plugins on top of our base image. 
https://github.com/linuxserver/docker-mods

This program is weird because there are so many use cases and so many plugins , it is tough to officially support them all. 
Let me know if you are interested.

**Comment by rawdlite** [comment]
Cool, i will have a look when im back from my holidays.

**Comment by thelamer** [comment]
@rawdlite Let me know if you have any questions about the Mods, it is something we have used internally and for connected projects. 
Even if it is just init scripts to install deps, I would like to include it as an option in the Readme so power users have a semi official channel to follow for greater plugin support.

**Comment by hannah98** [comment]
I was looking for the same thing as @rawdlite and followed the link @thelamer gave about Docker mods.  I pretty much just copied the example mod and tweaked it to install the mod.  So far it seems to have worked just fine - my running container displays this output:

```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying furiousgeorge/beets-alternative-mod:latest files to container
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
...
Running furiousgeorge/beets-alternative-mod installation of beets-alternatives
Collecting beets-alternatives
  Downloading https://files.pythonhosted.org/packages/ac/b5/e11fc20c9798d6c43d3a081e313a4d1280f6a6accf408e1783d26ede4d30/beets_alternatives-0.10.1-py3-none-any.whl
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3.8/site-packages (from beets-alternatives) (1.13.0)
Requirement already satisfied, skipping upgrade: beets>=1.4.7 in /usr/lib/python3.8/site-packages (from beets-alternatives) (1.4.9)
Requirement already satisfied, skipping upgrade: mutagen>=1.33 in /usr/lib/python3.8/site-packages (from beets>=1.4.7->beets-alternatives) (1.43.0)
Requirement already satisfied, skipping upgrade: unidecode in /usr/lib/python3.8/site-packages (from beets>=1.4.7->beets-alternatives) (1.1.1)
Requirement already satisfied, skipping upgrade: musicbrainzngs>=0.4 in /usr/lib/python3.8/site-packages (from beets>=1.4.7->beets-alternatives) (0.6)
Requirement already satisfied, skipping upgrade: pyyaml in /usr/lib/python3.8/site-packages (from beets>=1.4.7->beets-alternatives) (5.2)
Requirement already satisfied, skipping upgrade: munkres>=1.0.0 in /usr/lib/python3.8/site-packages (from beets>=1.4.7->beets-alternatives) (1.1.2)
Requirement already satisfied, skipping upgrade: jellyfish in /usr/lib/python3.8/site-packages (from beets>=1.4.7->beets-alternatives) (0.7.2)
Installing collected packages: beets-alternatives
Successfully installed beets-alternatives-0.10.1
[cont-init.d] 29-config-custom: exited 0.
```

I ran the help command for the beets-alternative plugin and had good output as well:

```
docker exec -it beets beet alt -h
usage: beet alt [-h] {update} ...

positional arguments:
  {update}

optional arguments:
  -h, --help  show this help message and exit
```

Here is the link to my repo [https://github.com/hannah98/beets-alternative-mod](https://github.com/hannah98/beets-alternative-mod)

I don't know if there is a process to get this mod/plugin more widely available.  I do not need to own it (but will if it doesn't have a better home since I need to use it).

At a minimum I thought I would add these notes to this issue so that other people could have a way to install this plugin.

**Comment by aptalca** [comment]
@hannah98 nice work!!

We haven't yet decided how exactly we are going to handle promoting docker mods. Bounced around some ideas around whether we should host or the community users and how we would list, vet, etc. It's still in early stages but we'll figure it out soon enough.

**Comment by hannah98** [comment]
Makes sense - beets can definitely get complicated.  Once you wind up with a long-term solution I'll be happy to shut down my repo with a message pointing to your solution.  I am thankful for the docker mod idea in your containers - I hadn't heard about it before but that is a very nice solution for situations like this.

**Comment by thelamer** [comment]
@hannah98 interested in spinning a couple of these up ? 
https://github.com/linuxserver/docker-mods

**Comment by DOFfactory** [comment]
I just landed on this page, and I was wondering whether it would not be possible instead of building separate docker mods just introduce an ENV variable, where a user would list all the plugins one wants to install, comma separated. This ENV will then be fed into the build process, whenever the container is built. I hate after every build logging into my beets container and re-download the same plugins all the time, esp. when one uses watchtower automatic updates.

**Comment by alexindigo** [comment]
Hey @hannah98, looks like your example repo is no longer up – https://github.com/hannah98/beets-alternative-mod
Curious to see what you did there.

**Comment by hannah98** [comment]
Hi @alexindigo.  I've had a request for a new branch located here so it could be an "official" mod:

https://github.com/linuxserver/docker-mods/issues/154

There's a link in that issue to my new repo:
https://github.com/hannah98/docker-mods/tree/beets-alternatives

That should be what you are looking for.

**Comment by alexindigo** [comment]
I see. Thanks a lot.
